# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7934c407a352625552865969dfa098a872f285a0c584bf0226062eca8027bfa5456ca71d0b925018003a1a8c8b83862877bdcf122113f4976040ae5c10e39c20

test:
  secret_key_base: 5fc8eb4a525c1804fcbdb43b4021d8106ece7da706893af7d3b7afdaf27446ebc15c8c6e7dec7fc7234f5e2e2d1a7f4a8bf2052d7c1bb7b1d03469715ad31bb2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
